### ISSUE TITLE
Sale Period

### ISSUE THREAD

**Issue by phillux** [LasticXYZ/price-simulation#4]
According to [RFC-1](https://github.com/polkadot-fellows/RFCs/blob/6f29561a4747bbfd95307ce75cd949dfff359e39/text/0001-agile-coretime.md?plain=1#L164), there is a lead-in period and the remainder of the purchasing period before the timeslice of the region begins to be utilized. 

This doesn't seem to be reflected in the price simulation model here which could lead to miscalculations and false expectation.

I couldn't find anywhere in the broker pallet where this was defined though.

**Comment by poppyseedDev** [comment]
Maybe I don't understand the question.
This is the leadin_period

<img width="138" alt="Screenshot 2023-11-01 at 11 14 27" src="https://github.com/LasticXYZ/price-simulation/assets/30662672/99e35d27-87ce-43d5-a62a-3d36d47d5e74">

<img width="737" alt="Screenshot 2023-11-01 at 11 13 52" src="https://github.com/LasticXYZ/price-simulation/assets/30662672/a548f328-7f93-4246-9137-84562f36d3e1">


<img width="737" alt="Screenshot 2023-11-01 at 11 13 34" src="https://github.com/LasticXYZ/price-simulation/assets/30662672/4483ebff-7fd0-4bcd-8aa8-51e73974d1ac">

**Comment by poppyseedDev** [comment]
leadin_length in the substrate code:

<img width="556" alt="Screenshot 2023-11-01 at 11 21 44" src="https://github.com/LasticXYZ/price-simulation/assets/30662672/7c511133-765c-433d-a91b-bdeb21b8f966">

**Comment by poppyseedDev** [comment]
Refers to #22 

@pieri93 if you have any insights
